### PR TITLE
Add `services` subcommand

### PR DESCRIPTION
**Pull request by rwaweber**
Lazy copy of logs command, uses naive web-scraping  to show services on a gokrazy instance.
There's probably a better way to do this, just the lowest effort method I came to.
More than happy to try to tackle this in a different way!

### CODE REVIEW

**Comment by stapelberg** [comment]
Hey, thanks for your PR! 

What’s the use-case for this command? If you’re interested in the services, why not just consult the config.json instead of querying the device?

**Comment by rwaweber** [comment]
Hey @stapelberg! Thanks for maintaining this project, I've had a lot of fun getting it up and running.

That approach definitely works too!

I suppose in my mental model, I had been curious about the state of installed services of a given device, rather than the local "desired state".

One instance that comes to mind is a possible situation where the local configuration may have been out of sync with the device.

e.g. a bad/misconfigured deployment, but I never came back to fix it - I'd need to log in to the web interface to see what services were available.

Thinking out loud, _maybe_ it'd make sense to forgo the webscraping here, and investigate more of a "remote process controller" kind of approach?

Something along the lines of:
- Updating the GET `/status` route so that without any parameters, it listed all installed services and their state(stopped, restarting, running)
-  Using the existing `/restart` route to control a given service? 

Where from the CLI, one could:
```
gok -i <instance> service list
```
Which would list the installed services and their current state

And to support the other runtime operations:
``` 
gok -i <instance> service run-once -s <service>
gok -i <instance> service stop -s <service>
gok -i <instance> service supervise -s <service>
```

I know  this is sort of increasing in scope a little more than I had intended, but do you think a UX sort of like that would be helpful? Happy to close and branch this out into separate issues/thoughts if you'd like.

**Comment by stapelberg** [comment]
> Thanks for maintaining this project, I've had a lot of fun getting it up and running.

I’m glad you like it!

> e.g. a bad/misconfigured deployment, but I never came back to fix it - I'd need to log in to the web interface to see what services were available.

I would recommend opening the web interface in any case, as the web interface presents a lot of information that helps you understand the state of the device. E.g., the build timestamp, kernel version, list of services with their log messages, free disk space, etc.

As much as I’m a fan of the CLI, it’s hard to display the same information as nicely.

> * Updating the GET `/status` route so that without any parameters, it listed all installed services and their state(stopped, restarting, running)

This is already the case, but for the / handler: https://github.com/gokrazy/gokrazy/blob/edba3d33ffa9ec9d281a9073309fa9f72575ab97/status.go#L391

Try it out on the CLI: 

```
% curl --header 'Accept: application/json' http://gokrazy:secret@hostname/ | jq '.'
```

> * Using the existing `/restart` route to control a given service?

Also already possible, though a bit fiddly because of the XSRF protection. Here’s some example code from the breakglass tool that deals with that: https://github.com/gokrazy/breakglass/blob/158f63b4afb1fff3621262099791044ae725b117/cmd/breakglass/breakglass.go#L76-L121

> I know this is sort of increasing in scope a little more than I had intended, but do you think a UX sort of like that would be helpful?

The CLI commands in gokrazy are primarily provided as building blocks for automation. I can’t see a decent use-case for restarting individual services from the CLI, other than “I prefer it over clicking buttons in a browser”. I’m a bit worried about maintenance overhead and bit-rot when accepting a second way of doing things into the project. 

We already have some higher-level building blocks for *replacing a service with a new version* (`gok run`) or *following the service logs* (`gok logs`). These are available to easily construct a quick edit-run loop. 

I’m thinking a `gok service` is a little too low-level to fit, but maybe I’m missing something?

**Comment by rwaweber** [comment]
> The CLI commands in gokrazy are primarily provided as building blocks for automation. I can’t see a decent use-case for restarting individual services from the CLI, other than “I prefer it over clicking buttons in a browser”

You caught me redhanded! 😂  That's definitely the case here. 😄 

> I’m a bit worried about maintenance overhead and bit-rot when accepting a second way of doing things into the project.

That is extremely valid and I totally understand. Happy to close that in this case. ❤️ 

I do have another question, that I'll follow up with in a more appropriate place.

Thanks for the clear reasoning and communication!

**Pull request closed without merging**
