### PR TITLE
Support i386/x86 platforms

### PR DESCRIPTION
**Pull request by george-hopkins**
Add support for x86 platforms (`GOARCH=386`) by ensuring the kernel arch gets detected correctly and the proper GPT partition type is chosen.

### CODE REVIEW

**Review by stapelberg — APPROVED** [review]

**Comment by stapelberg** [comment]
Can you please rebase this PR to pick up commit https://github.com/gokrazy/tools/commit/d0d0a0a6aeabe13ffdb477d0cdd79ea3c85a47ca please? That should fix the failing GitHub Actions run, which is unrelated to your changes.

**Comment by george-hopkins** [comment]
Done. With the other PRs already reviewed, this change should be last one to run gokrazy on x86. In my case, I use it to revive some PC-Engines boards.

**Comment by stapelberg** [comment]
> Done. With the other PRs already reviewed, this change should be last one to run gokrazy on x86. In my case, I use it to revive some PC-Engines boards.

Must be quite an old board? All PC Engines machines I have are amd64.

**Review by stapelberg — APPROVED** [review]

**Comment by george-hopkins** [comment]
Yes, I still have some ALIX boards around. However, I should probably replace them with more efficient boards.

**Pull request merged**
